baseURL = "https://leisure.pages.dev"
languageCode = "zh-tw"
title = "小蚂蚁的乐园"
theme = "hugo-theme-monochrome"
defaultContentLanguage = "zh-tw"
enableEmoji = true
paginate = 5

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]
