baseURL = "https://purpleleaf.top/"
languageCode = "zh-tw"
title = "小蚂蚁的乐园"
theme = "hugo-theme-monochrome"
defaultContentLanguage = "zh-tw"
enableEmoji = true
paginate = 5
google-site-verification = true

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]

