baseURL = "https://purpleleaf.top/"
languageCode = "zh-tw"
title = "小蚂蚁的乐园"
theme = "hugo-theme-monochrome"
defaultContentLanguage = "zh-tw"
enableEmoji = true
paginate = 5

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
description = "小蚂蚁的个人博客,linux,termux,docker,哲学思考，生活感悟"
